[features]
seeds = false
skip-lint = false

[programs.devnet]
fee_governance_hub = "B2MAnZ2rRrespfWjFbq6jxp6BFDZ35wPQtMHY4zd3iFD"

[programs.mainnet]
fee_governance_hub = "B2MAnZ2rRrespfWjFbq6jxp6BFDZ35wPQtMHY4zd3iFD"

[registry]
url = "https://api.apr.dev"

[provider]
# Default to devnet
cluster = "***REMOVED***"
wallet = "../roundies_devnet.json"

# Devnet configuration
[provider.devnet]
cluster = "***REMOVED***"
wallet = "../roundies_devnet.json"

# Mainnet configuration
[provider.mainnet]
cluster = "https://mainnet.helius-rpc.com/?api-key=YOUR_MAINNET_API_KEY"
wallet = "../roundies_mainnet.json"  # Create this wallet file for mainnet

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test.ts"
build = "anchor build && cp target/types/fee_governance_hub.ts fee-governance-hub-ts/src/idl/fee_governance_hub.ts && cp target/idl/fee_governance_hub.json fee-governance-hub-ts/src/idl/fee_governance_hub.json"
